default: &default
  adapter: mysql2
  encoding: utf8
  charset: utf8
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  username: <%= ENV.fetch('MYSQL_USERNAME', 'root') %>
  password: <%= ENV.fetch('MYSQL_PASSWORD', 'password') %>
  host: <%= ENV.fetch('MYSQL_HOST', 'db') %>

development:
  <<: *default
  database: development

test:
  <<: *default
  database: test

production:
  <<: *default
